project_id = "rpxbhmgwgnavxxeqwsbg"

[functions.run-scheduled-tasks]
verify_jwt = false

[functions.analytics-ingest]
verify_jwt = false

[functions.deploy-info]
verify_jwt = false

[functions.terminal-ai]
verify_jwt = false


